Emacs: sh snippets update

diff --git a/.emacs.d/snippets/sh-mode/check b/.emacs.d/snippets/sh-mode/check
--- a/.emacs.d/snippets/sh-mode/check
+++ b/.emacs.d/snippets/sh-mode/check
@@ -5,7 +5,7 @@ check()
 {
     for i ; do
         if ! command -v \$i >/dev/null 2>&1; then
-            echo >&2 "\'$i' not found in PATH. Exiting."
+            echo "\'$i' not found in PATH. Exiting." >&2
             exit 1
         fi
     done
diff --git a/.emacs.d/snippets/sh-mode/notcmd b/.emacs.d/snippets/sh-mode/notcmd
--- a/.emacs.d/snippets/sh-mode/notcmd
+++ b/.emacs.d/snippets/sh-mode/notcmd
@@ -2,6 +2,6 @@
 # key: notcmd
 # --
 if ! command -v $1 >/dev/null 2>&1; then
-    echo >&2 "'$1' not found in PATH. Exiting."
+    echo "'$1' not found in PATH. Exiting." >&2
     exit 1
 fi
