scripts: Reformat with tabs and more consistent style

diff --git a/.scripts/.tc-video-custom.in b/.scripts/.tc-video-custom.in
--- a/.scripts/.tc-video-custom.in
+++ b/.scripts/.tc-video-custom.in
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp()
-{
-    cat <<EOF
+_usage () {
+	cat <<EOF
 Usage: ${1##*/} MODE
 
 This script was generated with tc-video-custom.
@@ -22,56 +21,50 @@ EOF
 SAMPLE=""
 OPT_PROCESS=false
 while getopts ":hef" opt; do
-    case $opt in
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        e)
-            SAMPLE="-ss 60 -t 60"
-            OPT_PROCESS=true ;;
-        f)
-            OPT_PROCESS=true ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-        :)
-            echo "Missing argument."
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	h)
+		_usage "$0"
+		exit 1 ;;
+	e)
+		SAMPLE="-ss 60 -t 60"
+		OPT_PROCESS=true ;;
+	f)
+		OPT_PROCESS=true ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
 done
 
 shift $(($OPTIND - 1))
 
 if ! $OPT_PROCESS; then
-    _printhelp "$0"
-    exit
+	_usage "$0"
+	exit
 fi
 
 if ! command -v ffmpeg >/dev/null 2>&1; then
-    echo >&2 "'ffmpeg' not found in PATH. Exiting."
-    exit 1
+	echo >&2 "'ffmpeg' not found in PATH. Exiting."
+	exit 1
 fi
 
-_transcode ()
-{
-    ## You can choose here to process all files at the same time. Useful if you
-    ## need to remux streams or to concatenate.
-    # ffmpeg -i ###FILELIST \
-    ffmpeg -nostdin -i "$@" \
-        -c:v libx264 -preset slow -crf 20 \
-        -c:a libvorbis -b:a 192k -ac 2 \
-        -c:s copy \
-        -map 0 \
-        $SAMPLE \
-        "${1%.*}-$(date '+%F-%H%M%S').mkv"
+_transcode () {
+	## You can choose here to process all files at the same time. Useful if you
+	## need to remux streams or to concatenate.
+	# ffmpeg -i ###FILELIST \
+	ffmpeg -nostdin -i "$@" \
+		-c:v libx264 -preset slow -crf 20 \
+		-c:a libvorbis -b:a 192k -ac 2 \
+		-c:s copy \
+		-map 0 \
+		$SAMPLE \
+		"${1%.*}-$(date '+%F-%H%M%S').mkv"
 }
 
 set -- ###FILENAMES
 
 ## Choose to process all files one after another.
 for i ; do
-    _transcode "$i"
+	_transcode "$i"
 done
 
 ## Or all files at the same time. You have to change the ffmpeg input in the
diff --git a/.scripts/abs-wrapper b/.scripts/abs-wrapper
--- a/.scripts/abs-wrapper
+++ b/.scripts/abs-wrapper
@@ -4,9 +4,8 @@
 UPSTREAM_SOURCE="srcdir"
 ## End of user config
 
-_printhelp ()
-{
-    cat <<EOF
+_usage () {
+	cat <<EOF
 Usage: ${1##*/} [OPTIONS] PACKAGES
 
 WARNING: development version. Not reliable for AUR-dependency resolution.
@@ -39,15 +38,15 @@ Options:
 Example:
   ${1##*/} -icf \$(pacman -Qmq)
 
-     For all foreign installed packages, force fetch PKGBUILD, fetch source code
-     if not available, build if not already build, force installing and clean
-     build folder.
+    For all foreign installed packages, force fetch PKGBUILD, fetch source code
+    if not available, build if not already build, force installing and clean
+    build folder.
 
   ${1##*/} -sbicf nawk ncdu
 
-     For all foreign installed packages, fetch PKGBUILD and source code if not
-     available, force build if not already build, force installing and clean
-     build folder.
+    For all foreign installed packages, fetch PKGBUILD and source code if not
+    available, force build if not already build, force installing and clean
+    build folder.
 
 EOF
 }
@@ -63,46 +62,60 @@ OPT_INSTALL=false
 OPT_SOURCE=false
 
 while getopts ":bcCfhis" opt; do
-    case $opt in
-        b)
-            OPT_BUILD=true ;;
-        c)
-            MAKEPKG_OPT="$MAKEPKG_OPT -c"
-            OPT_CLEAN=true ;;
-        C)
-            OPT_MRPROPER=true ;;
-        f)
-            MAKEPKG_OPT="$MAKEPKG_OPT -f"
-            PACMAN_OPT=""
-            OPT_FORCE=true ;;
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        i)
-            OPT_INSTALL=true ;;
-        s)
-            OPT_SOURCE=true ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-        :)
-            echo "Missing argument."
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	b)
+		OPT_BUILD=true ;;
+	c)
+		MAKEPKG_OPT="$MAKEPKG_OPT -c"
+		OPT_CLEAN=true ;;
+	C)
+		OPT_MRPROPER=true ;;
+	f)
+		MAKEPKG_OPT="$MAKEPKG_OPT -f"
+		PACMAN_OPT=""
+		OPT_FORCE=true ;;
+	h)
+		_usage "$0"
+		exit 1 ;;
+	i)
+		OPT_INSTALL=true ;;
+	s)
+		OPT_SOURCE=true ;;
+	\?)
+		echo 'HO'
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
+
+usage () {
+	cat<<EOF
+Usage: ${1##*/} [OPTIONS] FILES
+
+Options:
+
+  -h:  Show this help.
+
+EOF
+}
+
+shift $(($OPTIND - 1))
+if [ $# -eq 0 ]; then
+	usage "$0"
+	exit 1
+fi
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    echo "Missing argument."
-    _printhelp "$0"
-    exit 1
+	echo "Missing argument."
+	_usage "$0"
+	exit 1
 fi
 
 if ! command -v makepkg >/dev/null; then
-    echo "You need makepkg to run this script."
-    exit 1
+	echo "You need makepkg to run this script."
+	exit 1
 fi
 
 HAS_ABS=false
@@ -111,123 +124,115 @@ command -v abs >/dev/null && HAS_ABS=true
 command -v yaourt >/dev/null && HAS_YAOURT=true
 
 if ! $HAS_ABS && ! $HAS_YAOURT; then
-    echo "Please install either an ABS-tree or yaourt."
-    exit 1
+	echo "Please install either an ABS-tree or yaourt."
+	exit 1
 fi
 
 if $HAS_ABS && [ -f "/etc/abs.conf" ]; then
-    . "/etc/abs.conf"
-    [ "$ABSROOT" = "" ] && ABSROOT="/var/abs/"
+	. "/etc/abs.conf"
+	[ "$ABSROOT" = "" ] && ABSROOT="/var/abs/"
 fi
 
 ################################################################################
 
-abs_pkgbuild ()
-{
-    pacman -Si $1 >/dev/null 2>&1
-    if [ $? -eq 0 ] && $HAS_ABS && [ -d "$ABSROOT" ]; then
-        cp -r /var/abs/*/$1 .
-    else
-        yaourt -G "$1" --noconfirm
-    fi
+abs_pkgbuild () {
+	pacman -Si $1 >/dev/null 2>&1
+	if [ $? -eq 0 ] && $HAS_ABS && [ -d "$ABSROOT" ]; then
+		cp -r /var/abs/*/$1 .
+	else
+		yaourt -G "$1" --noconfirm
+	fi
 }
 
-abs_source ()
-{
-    (cd "$1" && \
-        mkdir -p "$UPSTREAM_SOURCE" && \
-        SRCDEST="$UPSTREAM_SOURCE" makepkg -o)
+abs_source () {
+	(cd "$1" && \
+			mkdir -p "$UPSTREAM_SOURCE" && \
+			SRCDEST="$UPSTREAM_SOURCE" makepkg -o)
 }
 
 ## TODO: unused function. Add 'build all deps from source' parameter?
-abs_builddeps ()
-{
-    DEPLIST=$(awk -F"'" '/^(make)?depends *= *\(/,/\)/ {for (n=2 ; n<NF; n++) res=res $n " "} END {gsub(/ +/, " ", res); print res}' PKGBUILD)
-    (cd .. && abs-wrapper $DEPLIST)
+abs_builddeps () {
+	DEPLIST=$(awk -F"'" '/^(make)?depends *= *\(/,/\)/ {for (n=2 ; n<NF; n++) res=res $n " "} END {gsub(/ +/, " ", res); print res}' PKGBUILD)
+	(cd .. && abs-wrapper $DEPLIST)
 }
 
-abs_buildmissing ()
-{
-    DEPLIST="$(makepkg -s 2>&1 | awk -F: '/target not found/ {print $3}')"
-    cd ..
-    while IFS= read -r p; do
-        abs_pkgbuild $p
-        abs_build $p
-        abs_install $p
-    done <<EOF
-    ${DEPLIST}
+abs_buildmissing () {
+	DEPLIST="$(makepkg -s 2>&1 | awk -F: '/target not found/ {print $3}')"
+	cd ..
+	while IFS= read -r p; do
+		abs_pkgbuild $p
+		abs_build $p
+		abs_install $p
+	done <<EOF
+		${DEPLIST}
 EOF
-    cd $1
+	cd $1
 }
 
-abs_build ()
-{
-    (cd "$1" && \
-        mkdir -p "$UPSTREAM_SOURCE" && \
-        (makepkg -s || \
-        if [ $? -ne 0 ]; then abs_buildmissing $1; fi ) && \
-        SRCDEST="$UPSTREAM_SOURCE" makepkg -r $MAKEPKG_OPT --nocheck --noconfirm)
+abs_build () {
+	(cd "$1" && \
+			mkdir -p "$UPSTREAM_SOURCE" && \
+			(makepkg -s || \
+					if [ $? -ne 0 ]; then abs_buildmissing $1; fi ) && \
+			SRCDEST="$UPSTREAM_SOURCE" makepkg -r $MAKEPKG_OPT --nocheck --noconfirm)
 }
 
-abs_clean ()
-{
-    (cd "$1" && \
-        echo "Removing src/ and pkg/ folders." && \
-        rm -rf "src" "pkg")
+abs_clean () {
+	(cd "$1" && \
+			echo "Removing src/ and pkg/ folders." && \
+			rm -rf "src" "pkg")
 }
 
 
-abs_mrproper ()
-{
-    (cd "$1" && \
-        echo "Removing archives." && \
-        rm -v *.tar.gz *.tar.xz *.tar.bz *.tar.bz2 *.tgz *.txz *.tbz *.tbz2 2>/dev/null)
+abs_mrproper () {
+	(cd "$1" && \
+			echo "Removing archives." && \
+			rm -v *.tar.gz *.tar.xz *.tar.bz *.tar.bz2 *.tgz *.txz *.tbz *.tbz2 2>/dev/null)
 }
 
-abs_install ()
-{
-    sudo sh -c '
-        (cd "$0" && pacman '$PACMAN_OPT' --noconfirm -U *.pkg.tar.xz)
-        for i; do
-            (cd "$i" && pacman '$PACMAN_OPT' --noconfirm -U *.pkg.tar.xz)
-        done
+abs_install () {
+	sudo sh -c '
+		(cd "$0" && pacman '$PACMAN_OPT' --noconfirm -U *.pkg.tar.xz)
+		for i; do
+			(cd "$i" && pacman '$PACMAN_OPT' --noconfirm -U *.pkg.tar.xz)
+		done
 ' "$@"
 }
 
 for i ; do
-    echo "==> Processing $i."
+	echo "==> Processing $i."
 
-    ## Fetch PKGBUILD.
-    if [ ! -f "$i/PKGBUILD" ] || $OPT_FORCE; then
-        abs_pkgbuild "$i"
-    fi
+	## Fetch PKGBUILD.
+	if [ ! -f "$i/PKGBUILD" ] || $OPT_FORCE; then
+		abs_pkgbuild "$i"
+	fi
 
-    ## Skip because $i does not exist.
-    [ ! -d "$i" ] && continue
+	## Skip because $i does not exist.
+	[ ! -d "$i" ] && continue
 
-    ## Fetch source code.
-    if $OPT_SOURCE; then
-        abs_source "$i"
-    fi
+	## Fetch source code.
+	if $OPT_SOURCE; then
+		abs_source "$i"
+	fi
 
-    ## Build.
-    if $OPT_BUILD || ($OPT_INSTALL && [ ! -f $i/*.pkg.tar.xz ]); then
-        abs_build "$i"
-    fi
+	## Build.
+	if $OPT_BUILD || ($OPT_INSTALL && [ ! -f $i/*.pkg.tar.xz ]); then
+		abs_build "$i"
+	fi
 
-    ## Clean build folder.
-    if $OPT_CLEAN; then
-        abs_clean "$i"
-    fi
+	## Clean build folder.
+	if $OPT_CLEAN; then
+		abs_clean "$i"
+	fi
 
-    ## Remove archives.
-    if $OPT_MRPROPER; then
-        abs_mrproper "$i"
-    fi
+	## Remove archives.
+	if $OPT_MRPROPER; then
+		abs_mrproper "$i"
+	fi
 done
 
 ## Install packages. We put the install part outside the loop so that we prompt
 ## for password one time only.
 if $OPT_INSTALL; then
-    abs_install "$@"
+	abs_install "$@"
 fi
diff --git a/.scripts/archive b/.scripts/archive
--- a/.scripts/archive
+++ b/.scripts/archive
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp()
-{
-    cat <<EOF
+_usage () {
+	cat <<EOF
 Usage: ${1##*/} [-m METHOD] [-v] FILES|FOLDERS
 
 Create an archive in current folder from a single or multiples
@@ -27,84 +26,83 @@ ARCOPT="z"
 OPTIONS=""
 OPT_SPLIT=false
 while getopts ":him:sv" opt; do
-    case $opt in
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        i)
-            OPTIONS="$OPTIONS --owner=root --group=root --numeric-owner" ;;
-        m)
-            [ "$OPTARG" = "gz" ] && ARCEXT=".gz" && ARCOPT="z"
-            [ "$OPTARG" = "xz" ] && ARCEXT=".xz" && ARCOPT="J"
-            [ "$OPTARG" = "none" ] && ARCEXT="" && ARCOPT=""
-            ;;
-        s)
-            OPT_SPLIT=true ;;
-        v)
-            OPTIONS="$OPTIONS --exclude-vcs" ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	h)
+		_usage "$0"
+		exit 1 ;;
+	i)
+		OPTIONS="$OPTIONS --owner=root --group=root --numeric-owner" ;;
+	m)
+		[ "$OPTARG" = "gz" ] && ARCEXT=".gz" && ARCOPT="z"
+		[ "$OPTARG" = "xz" ] && ARCEXT=".xz" && ARCOPT="J"
+		[ "$OPTARG" = "none" ] && ARCEXT="" && ARCOPT=""
+		;;
+	s)
+		OPT_SPLIT=true ;;
+	v)
+		OPTIONS="$OPTIONS --exclude-vcs" ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    _printhelp "$0"
-    exit 1
+	_usage "$0"
+	exit 1
 fi
 
 ## We need 'realpath' since we need to work on the real path for the input
 ## files/folders and the archive location. Otherwise we could have troubles with
 ## circular symlinks and so on.
 if ! command -v realpath >/dev/null 2>&1; then
-    echo >&2 "'realpath' not found in PATH. Exiting."
-    exit 1
+	echo >&2 "'realpath' not found in PATH. Exiting."
+	exit 1
 fi
 
-_archive()
-{
-    ## Only one input entry: use it as base name for the archive.
-    if [ $# -eq 1 ]; then
-        REALPATH="$(realpath "$1")"
-        OUTFILE="${REALPATH##*/}-$(date +%F-%H%M%S).tar${ARCEXT}"
-    else
-        OUTFILE="${PWD##*/}-$(date +%F-%H%M%S).tar${ARCEXT}"
-    fi
+_archive () {
+	## Only one input entry: use it as base name for the archive.
+	if [ $# -eq 1 ]; then
+		REALPATH="$(realpath "$1")"
+		OUTFILE="${REALPATH##*/}-$(date +%F-%H%M%S).tar${ARCEXT}"
+	else
+		OUTFILE="${PWD##*/}-$(date +%F-%H%M%S).tar${ARCEXT}"
+	fi
 
-    REALPWD="$(realpath "$PWD")"
-    for i; do
-        REALPATH="$(realpath "$i")"
+	REALPWD="$(realpath "$PWD")"
+	for i; do
+		REALPATH="$(realpath "$i")"
 
-        ## Check if one of the arguments is current folder. We need to make sure the
-        ## archive is not created in an input folder, otherwise it will include
-        ## itself.
-        if [ "$REALPATH" = "$REALPWD" ]; then
-            OUTPATH="$(realpath "$REALPWD/..")"
-            break
-        fi
-    done
+		## Check if one of the arguments is current folder. We need to make sure the
+		## archive is not created in an input folder, otherwise it will include
+		## itself.
+		if [ "$REALPATH" = "$REALPWD" ]; then
+			OUTPATH="$(realpath "$REALPWD/..")"
+			break
+		fi
+	done
 
-    if [ ! -w "$OUTPATH" ]; then
-        echo "[$OUTPATH] is not writable. Exiting."
-        return
-    fi
+	if [ ! -w "$OUTPATH" ]; then
+		echo "[$OUTPATH] is not writable. Exiting."
+		return
+	fi
 
-    echo "==> [$OUTPATH/$OUTFILE]"
-    for i; do
-        REALPATH="$(realpath "$i")"
-        echo "${REALPATH}" >&2
-        echo "-C '${REALPATH%/*}'"
-        echo "${REALPATH##*/}"
-    done | tar $OPTIONS -${ARCOPT}cf "$OUTPATH/$OUTFILE" -T -
+	echo "==> [$OUTPATH/$OUTFILE]"
+	for i; do
+		REALPATH="$(realpath "$i")"
+		echo "${REALPATH}" >&2
+		echo "-C '${REALPATH%/*}'"
+		echo "${REALPATH##*/}"
+	done | tar $OPTIONS -${ARCOPT}cf "$OUTPATH/$OUTFILE" -T -
 }
 
 if $OPT_SPLIT; then
-    for j ; do
-        _archive "$j"
-    done
+	for j ; do
+		_archive "$j"
+	done
 else
-    _archive "$@"
+	_archive "$@"
 fi
diff --git a/.scripts/clonecd b/.scripts/clonecd
--- a/.scripts/clonecd
+++ b/.scripts/clonecd
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp ()
-{
-    cat<<EOF
+_usage () {
+	cat<<EOF
 Usage: ${1##*/} [OPTIONS] ISOFILE
 
 Dump optical disc to ISOFILE (without extension).
@@ -17,28 +16,28 @@ EOF
 
 DRIVE=/dev/sr0
 while getopts ":hd:" opt; do
-    case $opt in
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        d)
-            DRIVE=/dev/$OPTARG ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	h)
+		_usage "$0"
+		exit 1 ;;
+	d)
+		DRIVE=/dev/$OPTARG ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    _printhelp "$0"
-    exit 1
+	_usage "$0"
+	exit 1
 fi
 
 if ! command -v readcd >/dev/null 2>&1; then
-    echo >&2 "'readcd' not found in PATH. Exiting."
-    exit 1
+	echo >&2 "'readcd' not found in PATH. Exiting."
+	exit 1
 fi
 
 ## Fast?
diff --git a/.scripts/dataindex b/.scripts/dataindex
--- a/.scripts/dataindex
+++ b/.scripts/dataindex
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp ()
-{
-    cat<<EOF
+_usage () {
+	cat<<EOF
 Usage: ${1##*/} [OPTIONS] FOLDERS
 
 Output index of folder hierarchies to stdout. This is used as a small "backup"
@@ -20,54 +19,53 @@ EOF
 opt_noclobber=true
 opt_file=false
 while getopts ":fhw" opt; do
-    case $opt in
-        f)
-            opt_noclobber=false ;;
-        h)
-            _printhelp "$0"
-            exit 0 ;;
-        w)
-            opt_file=true ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	f)
+		opt_noclobber=false ;;
+	h)
+		_usage "$0"
+		exit 0 ;;
+	w)
+		opt_file=true ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    _printhelp "$0"
-    exit 1
+	_usage "$0"
+	exit 1
 fi
 
 ## 'realpath' is required in case argument is ending with '.' or '..'.
 if ! command -v realpath >/dev/null 2>&1; then
-    echo "'realpath' not found in PATH. Exiting." >&2
-    exit 1
+	echo "'realpath' not found in PATH. Exiting." >&2
+	exit 1
 fi
 
 for i ; do
-    ## Find over '.*' and '*', is bad practice since if will fail on
-    ## non-existing files or for files beginning with a dash. The 'printf'
-    ## command in find is for GNU find only.
+	## Find over '.*' and '*', is bad practice since if will fail on
+	## non-existing files or for files beginning with a dash. The 'printf'
+	## command in find is for GNU find only.
 
-    ## The two following lines do the same for the same time cost. The former is shorter.
-    # find "$i" -type f | awk -v str="$i" '{l=length(str)+2; print substr($0, l)}' | sort > "$OUTPUT"
+	## The two following lines do the same for the same time cost. The former is shorter.
+	# find "$i" -type f | awk -v str="$i" '{l=length(str)+2; print substr($0, l)}' | sort > "$OUTPUT"
 
-    ## 'LC_ALL=C sort' is required to make sure to output is consistent across
-    ## different systems.
-    (cd -- "$i" && find . -type f) | sed 's/^.\///' | LC_ALL=C sort | \
-    if $opt_file; then
-        i="$(realpath -- "$i")"
-        base="${i##*/}"
-        [ ! -d "$i" ] && continue
-        output="$base.index"
-        [ -e "$OUTPUT" ] && $opt_noclobber && output="$base-$(date +%F-%T).index"
-        echo "$output"
-        cat > "$output"
-    else
-        cat
-    fi
+	## 'LC_ALL=C sort' is required to make sure to output is consistent across
+	## different systems.
+	(cd -- "$i" && find . -type f) | sed 's/^.\///' | LC_ALL=C sort | \
+		if $opt_file; then
+			i="$(realpath -- "$i")"
+			base="${i##*/}"
+			[ ! -d "$i" ] && continue
+			output="$base.index"
+			[ -e "$OUTPUT" ] && $opt_noclobber && output="$base-$(date +%F-%T).index"
+			echo "$output"
+			cat > "$output"
+		else
+			cat
+		fi
 done
-
diff --git a/.scripts/elisp b/.scripts/elisp
--- a/.scripts/elisp
+++ b/.scripts/elisp
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp ()
-{
-    cat<<EOF
+_usage () {
+	cat<<EOF
 Usage: ${1##*/} [OPTIONS] SCRIPT [ARGS...]
 
 Run Emacs Lisp SCRIPT.
@@ -17,32 +16,32 @@ EOF
 OPT_BYTE=false
 OPT_CLEAN=false
 while getopts :bc OPT; do
-    case $OPT in
-        b)
-            OPT_BYTE=true ;;
-        c)
-            OPT_CLEAN=true ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $OPT in
+	b)
+		OPT_BYTE=true ;;
+	c)
+		OPT_CLEAN=true ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 if [ $# -eq 0 ]; then
-    _printhelp "$0"
-    exit 1
+	_usage "$0"
+	exit 1
 fi
 
 if ! command -v emacs >/dev/null 2>&1; then
-    echo 'emacs not found in PATH. Exiting.' >&2
-    exit 1
+	echo 'emacs not found in PATH. Exiting.' >&2
+	exit 1
 fi
 
 script="$1"
 if $OPT_BYTE && [ "${1##*.}" = "el" ]; then
-    script="${1%.*}.elc"
-    emacs -Q --batch -f batch-byte-compile "$1" 2>/dev/null
+	script="${1%.*}.elc"
+	emacs -Q --batch -f batch-byte-compile "$1" 2>/dev/null
 fi
 shift
 
diff --git a/.scripts/git-get b/.scripts/git-get
--- a/.scripts/git-get
+++ b/.scripts/git-get
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp ()
-{
-    cat<<EOF
+_usage () {
+	cat<<EOF
 Usage: ${1##*/} [OPTIONS] REPOS
 
 Clone multiple git repos from \$DOMAIN:\$USER.
@@ -19,32 +18,32 @@ EOF
 DOMAIN=bitbucket.org
 USER=ambrevar
 while getopts ":hd:u:" opt; do
-    case $opt in
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        d)
-            DOMAIN=$OPTARG ;;
-        u)
-            USER=$OPTARG ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	h)
+		_usage "$0"
+		exit 1 ;;
+	d)
+		DOMAIN=$OPTARG ;;
+	u)
+		USER=$OPTARG ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    _printhelp "$0"
-    exit 1
+	_usage "$0"
+	exit 1
 fi
 
 if ! command -v git >/dev/null 2>&1; then
-    echo >&2 "'git' not found in PATH. Exiting."
-    exit 1
+	echo >&2 "'git' not found in PATH. Exiting."
+	exit 1
 fi
 
 for i; do
-    git clone git@$DOMAIN:/$USER/$i
+	git clone git@$DOMAIN:/$USER/$i
 done
diff --git a/.scripts/imagemount b/.scripts/imagemount
--- a/.scripts/imagemount
+++ b/.scripts/imagemount
@@ -6,86 +6,83 @@
 FUSEROOT="$HOME/fuse"
 ################################################################################
 
-_mount ()
-{
-    [ ! -f "$1" ] && return
+_mount () {
+	[ ! -f "$1" ] && return
 
-    DEVICE="$(cdemu status | awk 'NR>2 && $2==0 {print $1; found=1; exit}  END {if(! found)print NR-2}')"
-    DEV_COUNT="$(cdemu device-mapping | awk 'END {print NR-3}')"
+	DEVICE="$(cdemu status | awk 'NR>2 && $2==0 {print $1; found=1; exit}  END {if(! found)print NR-2}')"
+	DEV_COUNT="$(cdemu device-mapping | awk 'END {print NR-3}')"
 
-    if [  $(cdemu status |  grep -c "$1") -gt 0 ]; then
-        echo "Image alredy mounted."
-        return
-    fi
+	if [  $(cdemu status |  grep -c "$1") -gt 0 ]; then
+		echo "Image alredy mounted."
+		return
+	fi
 
-    if [ $DEVICE -gt $DEV_COUNT ]; then
-        while [ $DEVICE -gt $DEV_COUNT ]; do
-            cdemu add-device
-            DEV_COUNT="$(cdemu device-mapping | awk 'END {print NR-3}')"
-        done
+	if [ $DEVICE -gt $DEV_COUNT ]; then
+		while [ $DEVICE -gt $DEV_COUNT ]; do
+			cdemu add-device
+			DEV_COUNT="$(cdemu device-mapping | awk 'END {print NR-3}')"
+		done
 
-        ## WARNING: adding a new device takes some time. If we want to avoid errors,
-        ## we need to sleep until it is ready.
-        echo "Waiting until ready..."
-        while [ -z "$(cdemu device-mapping | awk -v devnum=$DEV_COUNT 'NR>2 && $1==devnum {print $2}')" ]; do
-            sleep 1
-        done
+		## WARNING: adding a new device takes some time. If we want to avoid errors,
+		## we need to sleep until it is ready.
+		echo "Waiting until ready..."
+		while [ -z "$(cdemu device-mapping | awk -v devnum=$DEV_COUNT 'NR>2 && $1==devnum {print $2}')" ]; do
+			sleep 1
+		done
 
-    fi
+	fi
 
-    cdemu load $DEVICE "$1"
-    if [ $? -ne 0 ] && command -v fuseiso >/dev/null 2>&1; then
-        echo "Falling back to fuseiso."
+	cdemu load $DEVICE "$1"
+	if [ $? -ne 0 ] && command -v fuseiso >/dev/null 2>&1; then
+		echo "Falling back to fuseiso."
 
-        # LIST="$(mount | awk -v root="$FUSEROOT" '$1 == "fuseiso" && $3 ~ root {print $3}')"
-        LIST=$(mount | awk -v root="$FUSEROOT" '$1 == "fuseiso" && $3 ~ root {sub(/^fuseiso on /,"");sub(/ type fuse.fuseiso [^ ]*$/, ""); print $0}')
-        ALREADY="$(lsof -c fuseiso -F n | grep "$1")"
+		# LIST="$(mount | awk -v root="$FUSEROOT" '$1 == "fuseiso" && $3 ~ root {print $3}')"
+		LIST=$(mount | awk -v root="$FUSEROOT" '$1 == "fuseiso" && $3 ~ root {sub(/^fuseiso on /,"");sub(/ type fuse.fuseiso [^ ]*$/, ""); print $0}')
+		ALREADY="$(lsof -c fuseiso -F n | grep "$1")"
 
-        if [ -n "$ALREADY" ]; then
-            echo "Image alredy mounted."
-            return
-        fi
+		if [ -n "$ALREADY" ]; then
+			echo "Image alredy mounted."
+			return
+		fi
 
-        COUNT=0
-        while [ -n "$(echo "$LIST" | grep "$FUSEROOT/drive-$COUNT" )" ]; do
-            COUNT=$(($COUNT+1))
-        done
+		COUNT=0
+		while [ -n "$(echo "$LIST" | grep "$FUSEROOT/drive-$COUNT" )" ]; do
+			COUNT=$(($COUNT+1))
+		done
 
-        mkdir -p "$FUSEROOT/drive-$COUNT"
-        fuseiso -p "$1" "$FUSEROOT/drive-$COUNT"
+		mkdir -p "$FUSEROOT/drive-$COUNT"
+		fuseiso -p "$1" "$FUSEROOT/drive-$COUNT"
 
-    else
-        NODE="$(cdemu device-mapping | awk -v devnum=$DEVICE 'NR>2 && $1==devnum {print $2}')"
-        ## TODO: This is terrible, but checking cdemu status does not work. Maybe
-        ## a kernel limitation.
-        echo "Mounting..."
-        sleep 2
-        udiskie-mount "$NODE"
-    fi
+	else
+		NODE="$(cdemu device-mapping | awk -v devnum=$DEVICE 'NR>2 && $1==devnum {print $2}')"
+		## TODO: This is terrible, but checking cdemu status does not work. Maybe
+		## a kernel limitation.
+		echo "Mounting..."
+		sleep 2
+		udiskie-mount "$NODE"
+	fi
 
 }
 
 
-_umount ()
-{
-    [ ! -d "$1" ] && return
+_umount () {
+	[ ! -d "$1" ] && return
 
-    NODE="$(df | awk -v mount="$1" '$0 ~ mount {node=$1; gsub(/[^%]+% /, ""); if ($0 ~ mount){print node; exit}}')"
+	NODE="$(df | awk -v mount="$1" '$0 ~ mount {node=$1; gsub(/[^%]+% /, ""); if ($0 ~ mount){print node; exit}}')"
 
-    if [ -n "$NODE" ]; then
-        udiskie-umount "$1"
+	if [ -n "$NODE" ]; then
+		udiskie-umount "$1"
 
-        DEVICE=$(cdemu device-mapping | awk -v node="$NODE" '$2 == node {print $1; exit}')
-        cdemu unload $DEVICE
-    elif command -v fuseiso >/dev/null; then
-        fusermount -u "$1"
-        rmdir "$1" >/dev/null 2>&1
-    fi
+		DEVICE=$(cdemu device-mapping | awk -v node="$NODE" '$2 == node {print $1; exit}')
+		cdemu unload $DEVICE
+	elif command -v fuseiso >/dev/null; then
+		fusermount -u "$1"
+		rmdir "$1" >/dev/null 2>&1
+	fi
 }
 
-_printhelp ()
-{
-    cat<<EOF
+_usage () {
+	cat<<EOF
 Usage: ${1##*/} FILES
        ${1##*/} -u FOLDERS
 
@@ -102,43 +99,42 @@ EOF
 
 OPT_UNMOUNT=false
 while getopts ":hu" opt; do
-    case $opt in
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        u)
-            OPT_UNMOUNT=true ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	h)
+		_usage "$0"
+		exit 1 ;;
+	u)
+		OPT_UNMOUNT=true ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    _printhelp "$0"
-    exit 1
+	_usage "$0"
+	exit 1
 fi
 
-check()
-{
-    for i ; do
-        if ! command -v $i >/dev/null 2>&1; then
-            echo >&2 "'$i' not found in PATH. Exiting."
-            exit 1
-        fi
-    done
+check () {
+	for i ; do
+		if ! command -v $i >/dev/null 2>&1; then
+			echo >&2 "'$i' not found in PATH. Exiting."
+			exit 1
+		fi
+	done
 }
 ## realpath is needed to check if image was already mounted or not.
 check udiskie cdemu realpath
 
 if $OPT_UNMOUNT; then
-    for i ; do
-        _umount "$(realpath "$i")"
-    done
+	for i ; do
+		_umount "$(realpath "$i")"
+	done
 else
-    for i ; do
-        _mount "$(realpath "$i")"
-    done
+	for i ; do
+		_mount "$(realpath "$i")"
+	done
 fi
diff --git a/.scripts/netinit b/.scripts/netinit
--- a/.scripts/netinit
+++ b/.scripts/netinit
@@ -4,19 +4,19 @@
 ## better off running the dhcpcd daemon with
 ## /etc/wpa_supplicant/wpa_supplicant.conf configured if needed. See
 ## dhcpcd-run-hooks(8).
-
+##
 ## Deps: wpa_supplicant, ccrypt (optional)
-
+##
 ## We need to use wpa_supplicant's unencrypted config file. We store it in a
 ## variable to keep it secure, but the 'wpa_supplicant' command requires a
 ## file. We cannot use a pipe for that, because in that case the config would be
 ## accessible unencrypted. So we need to use an internal path with a syntax like
 ## <(...) which is not specified by POSIX. Ksh, bash and Zsh can handle it.
-
+##
 ## Use 'wpa_passphrase ESSID $PW >> /etc/wpa_supplicant.conf', where PW is a
 ## variable containing the password.  You can set PW securely by using a shell
 ## built-in like 'read -s PW'.
-
+##
 ## There is an Emacs plugin for editing crypted files directly. See 'man
 ## ccrypt'.
 
@@ -25,9 +25,8 @@ TIMEOUT_LIMIT=500
 USE_DHCP=0
 USE_CRYPT=0
 
-_printhelp ()
-{
-    cat<<EOF
+_usage () {
+	cat<<EOF
 Usage: ${1##*/} [OPTIONS]
 
 Connect to a wireless network.
@@ -42,48 +41,48 @@ EOF
 }
 
 while getopts ":cdht:w:" opt; do
-    case $opt in
-        h)
-            _printhelp "$0"
-            return 1 ;;
-        c)
-            USE_CRYPT=1 ;;
-        d)
-            USE_DHCP=1 ;;
-        t)
-            TIMEOUT_LIMIT=$OPTARG ;;
-        w)
-            WSFILE="$OPTARG" ;;
-        ?)
-            _printhelp "$0"
-            return 1 ;;
-    esac
+	case $opt in
+	h)
+		_usage "$0"
+		return 1 ;;
+	c)
+		USE_CRYPT=1 ;;
+	d)
+		USE_DHCP=1 ;;
+	t)
+		TIMEOUT_LIMIT=$OPTARG ;;
+	w)
+		WSFILE="$OPTARG" ;;
+	\?)
+		_usage "$0"
+		return 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [ $(id -u) -ne 0 ]; then
-    echo "You must be root to run this script."
-    exit
+	echo "You must be root to run this script."
+	exit
 fi
 
 if [ $USE_CRYPT -eq 1 ]; then
-    if ! command -v ccat >/dev/null 2>&1; then
-        echo >&2 "'ccat' not found in PATH. Exiting."
-        exit 1
-    fi
+	if ! command -v ccat >/dev/null 2>&1; then
+		echo >&2 "'ccat' not found in PATH. Exiting."
+		exit 1
+	fi
 
-    WPA_SUPPLICANT_CONF="$(ccat "$WSFILE")"
-    if [ $? -ne 0 ]; then
-        echo "Failed to decrypt wpa_supplicant config from $WSFILE."
-        exit
-    fi
+	WPA_SUPPLICANT_CONF="$(ccat "$WSFILE")"
+	if [ $? -ne 0 ]; then
+		echo "Failed to decrypt wpa_supplicant config from $WSFILE."
+		exit
+	fi
 else
-    WPA_SUPPLICANT_CONF="$(cat "$WSFILE")"
-    if [ $? -ne 0 ]; then
-        echo "Failed to get wpa_supplicant config from $WSFILE."
-        exit
-    fi
+	WPA_SUPPLICANT_CONF="$(cat "$WSFILE")"
+	if [ $? -ne 0 ]; then
+		echo "Failed to get wpa_supplicant config from $WSFILE."
+		exit
+	fi
 fi
 
 ## Note: systemd-197 introduced Predictable Network Interface Names, so we need
@@ -94,41 +93,41 @@ NET_INTERFACE=$(ls -1 /sys/class/net | grep -m1 "^wl")
 pkill wpa_supplicant
 
 if [ "$OSTYPE" = "linux-gnu" ] ; then
-    ## Clean running processes if any.
-    pkill dhcpcd
+	## Clean running processes if any.
+	pkill dhcpcd
 
-    ## In case network inteface is not up.
-    ip link set ${NET_INTERFACE} up
+	## In case network inteface is not up.
+	ip link set ${NET_INTERFACE} up
 
-    # Associate if needed.
-    if [ "$1" = "-f" ] || [ -z "$(iw dev ${NET_INTERFACE} link | grep SSID)" ]; then
-        wpa_supplicant -B -i ${NET_INTERFACE} -D wext -c <(echo "${WPA_SUPPLICANT_CONF}")
-    fi
+	# Associate if needed.
+	if [ "$1" = "-f" ] || [ -z "$(iw dev ${NET_INTERFACE} link | grep SSID)" ]; then
+		wpa_supplicant -B -i ${NET_INTERFACE} -D wext -c <(echo "${WPA_SUPPLICANT_CONF}")
+	fi
 
-    ## Wait until wpa_supplicant has finished association.
-    i=0
-    while [ -z "$(iw dev ${NET_INTERFACE} link | grep SSID)" ] && [ $i -lt $TIMEOUT_LIMIT ] ; do
-        i=$(($i+1))
-    done
+	## Wait until wpa_supplicant has finished association.
+	i=0
+	while [ -z "$(iw dev ${NET_INTERFACE} link | grep SSID)" ] && [ $i -lt $TIMEOUT_LIMIT ] ; do
+		i=$(($i+1))
+	done
 
-    ## Get IP.
-    [ $USE_DHCP -eq 1 ] && dhcpcd ${NET_INTERFACE}
+	## Get IP.
+	[ $USE_DHCP -eq 1 ] && dhcpcd ${NET_INTERFACE}
 
 else
-## BSD
-## Same comments as for Linux.
+	## BSD
+	## Same comments as for Linux.
 
-    pkill dhclient
-    ifconfig wlan0 up
+	pkill dhclient
+	ifconfig wlan0 up
 
-    if [ -n "$(ifconfig ${NET_INTERFACE} | grep 'ssid ""')" ]; then
-        wpa_supplicant -B -i ${NET_INTERFACE} -c <(echo "${WPA_SUPPLICANT_CONF}")
-    fi
+	if [ -n "$(ifconfig ${NET_INTERFACE} | grep 'ssid ""')" ]; then
+		wpa_supplicant -B -i ${NET_INTERFACE} -c <(echo "${WPA_SUPPLICANT_CONF}")
+	fi
 
-    i=0
-    while [ -n "$(ifconfig ${NET_INTERFACE} | grep 'ssid ""')" ] && [ $i -lt $TIMEOUT_LIMIT ] ; do
-        i=$(($i+1))
-    done
+	i=0
+	while [ -n "$(ifconfig ${NET_INTERFACE} | grep 'ssid ""')" ] && [ $i -lt $TIMEOUT_LIMIT ] ; do
+		i=$(($i+1))
+	done
 
-    [ $USE_DHCP -eq 1 ] && dhclient ${NET_INTERFACE}
+	[ $USE_DHCP -eq 1 ] && dhclient ${NET_INTERFACE}
 fi
diff --git a/.scripts/netmap b/.scripts/netmap
--- a/.scripts/netmap
+++ b/.scripts/netmap
@@ -1,22 +1,22 @@
 #!/bin/sh
 
 if [ $# -ne 1 ] || [ "$1" = "-h" ] ; then
-    cat<<EOF
+	cat<<EOF
 Usage: ${1##*/} IP
 
 Print the map of the network associated to the provided IP.
 EOF
-    exit
+	exit
 fi
 
 ## Network operations
 if ! command -v nmap >/dev/null 2>&1; then
-    echo >&2 "'nmap' not found in PATH. Exiting."
-    exit 1
+	echo >&2 "'nmap' not found in PATH. Exiting."
+	exit 1
 fi
 
 echo "$1"
 for SCANIP in $( nmap -sL "$1" | grep -i "\([[:digit:]]\+\.\)\{3,\}[[:digit:]]\+" | awk '{print $5}' ); do
-    sudo nmap -oX - -n -sT -T Normal -O -sR -I -F -P0 "$SCANIP"
-    echo
+	sudo nmap -oX - -n -sT -T Normal -O -sR -I -F -P0 "$SCANIP"
+	echo
 done
diff --git a/.scripts/netscan b/.scripts/netscan
--- a/.scripts/netscan
+++ b/.scripts/netscan
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 if ! command -v nmap >/dev/null 2>&1; then
-    echo >&2 "'nmap' not found in PATH. Exiting."
-    exit 1
+	echo >&2 "'nmap' not found in PATH. Exiting."
+	exit 1
 fi
 
 SUBNET="$(ifconfig | awk '/inet/ && $0 !~ "127.0.0.1" {gsub(/\.[0-9]+$/, ".*", $2) ; print $2}')"
diff --git a/.scripts/pacfiles b/.scripts/pacfiles
--- a/.scripts/pacfiles
+++ b/.scripts/pacfiles
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp()
-{
-    cat <<EOF
+_usage () {
+	cat <<EOF
 Usage: ${1##*/} [OPTIONS] PACKAGES
 
 Display size of files in PACKAGES.
@@ -16,30 +15,30 @@ EOF
 OPTION_SORT="cat"
 
 while getopts ":hn" opt; do
-    case $opt in
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        n)
-            OPTION_SORT="sort -h" ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	h)
+		_usage "$0"
+		exit 1 ;;
+	n)
+		OPTION_SORT="sort -h" ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    echo "Missing argument."
-    _printhelp "$0"
-    exit 1
+	echo "Missing argument."
+	_usage "$0"
+	exit 1
 fi
 
 ! command -v pacman >/dev/null && echo "You need pacman to run this script." && exit 1
 if [ $(pacman -Qq "$@" 2>/dev/null | wc -l) -eq 0 ]; then
-    echo "No valid package given." >&2
-    exit
+	echo "No valid package given." >&2
+	exit
 fi
 
 ## We use "eval" to be compatible with non-POSIX wordsplitting (e.g. zsh).
diff --git a/.scripts/pacman-diff b/.scripts/pacman-diff
--- a/.scripts/pacman-diff
+++ b/.scripts/pacman-diff
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-_printhelp()
-{
-    cat <<EOF
+_usage () {
+	cat <<EOF
 Usage: ${1##*/} [-m|-e] [-q] FILE
 
 Display packages listed in FILE but not installed.
@@ -19,33 +18,33 @@ OPTION_FOREIGN=""
 OPTION_LOCAL="-1"
 
 while getopts ":hmqe" opt; do
-    case $opt in
-        e)
-            OPTION_EXPLICIT="e" ;;
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        m)
-            OPTION_FOREIGN="m" ;;
-        q)
-            OPTION_LOCAL="-2" ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	e)
+		OPTION_EXPLICIT="e" ;;
+	h)
+		_usage "$0"
+		exit 1 ;;
+	m)
+		OPTION_FOREIGN="m" ;;
+	q)
+		OPTION_LOCAL="-2" ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    echo "Missing argument."
-    _printhelp "$0"
-    exit 1
+	echo "Missing argument."
+	_usage "$0"
+	exit 1
 fi
 
 if ! command -v pacman >/dev/null 2>&1; then
-    echo >&2 "'pacman' not found in PATH. Exiting."
-    exit 1
+	echo >&2 "'pacman' not found in PATH. Exiting."
+	exit 1
 fi
 
 PKGLIST="$(mktemp)"
@@ -57,4 +56,3 @@ rm -f "$PKGLIST" "$FILE"
 
 ## Zsh version.
 # comm -3 ${OPTION_LOCAL} <(pacman -Qq${OPTION_FOREIGN}${OPTION_EXPLICIT} | sort) <(sort "$*")
-
diff --git a/.scripts/tc-video-generic b/.scripts/tc-video-generic
--- a/.scripts/tc-video-generic
+++ b/.scripts/tc-video-generic
@@ -2,9 +2,8 @@
 
 ## TODO: handle srt encoding?
 
-_printhelp()
-{
-    cat <<EOF
+_usage () {
+	cat <<EOF
 Usage: ${1##*/} [OPTIONS] FILES|FOLDERS
 
 Transcode FILES or files found in FOLDERS to desired format (default to .mkv
@@ -89,71 +88,69 @@ OPT_PREVIEW=false
 OPT_COPY=false
 
 while getopts ":a:b:cCe:fho:pPsS:tv:" opt; do
-    case $opt in
-        a)
-            AUDIO_CODEC=$OPTARG ;;
-        b)
-            AUDIO_DEFAULT_RATE=$OPTARG ;;
-        c)
-            VIDEO_PARAM="-c:v copy"
-            AUDIO_PARAM="-c:a copy"
-            OPT_COPY=true;;
-        C)
-            OPT_CROP=true;;
-        e)
-            EXT=$OPTARG;;
-        f)
-            OVERWRITE="-y"
-            OPT_OVERWRITE=true;;
-        h)
-            _printhelp "$0"
-            exit 1 ;;
-        o)
-            TC_VIDEO_OPT="$OPTARG" ;;
-        p)
-            OPT_PREVIEW=true ;;
-        P)
-            OPT_CROP=true
-            OPT_PREVIEW=true
-            OPT_CROPPREVIEW=true ;;
-        s)
-            SAMPLE="-ss 60 -t 360" ;;
-        S)
-            SAMPLE="-ss 60 -t $((60*$OPTARG))" ;;
-        t)
-            OPT_REMOVE_TITLE=true ;;
-        v)
-            VIDEO_PARAM="-c:v $OPTARG" ;;
-        ?)
-            _printhelp "$0"
-            exit 1 ;;
-    esac
+	case $opt in
+	a)
+		AUDIO_CODEC=$OPTARG ;;
+	b)
+		AUDIO_DEFAULT_RATE=$OPTARG ;;
+	c)
+		VIDEO_PARAM="-c:v copy"
+		AUDIO_PARAM="-c:a copy"
+		OPT_COPY=true;;
+	C)
+		OPT_CROP=true;;
+	e)
+		EXT=$OPTARG;;
+	f)
+		OVERWRITE="-y"
+		OPT_OVERWRITE=true;;
+	h)
+		_usage "$0"
+		exit 1 ;;
+	o)
+		TC_VIDEO_OPT="$OPTARG" ;;
+	p)
+		OPT_PREVIEW=true ;;
+	P)
+		OPT_CROP=true
+		OPT_PREVIEW=true
+		OPT_CROPPREVIEW=true ;;
+	s)
+		SAMPLE="-ss 60 -t 360" ;;
+	S)
+		SAMPLE="-ss 60 -t $((60*$OPTARG))" ;;
+	t)
+		OPT_REMOVE_TITLE=true ;;
+	v)
+		VIDEO_PARAM="-c:v $OPTARG" ;;
+	\?)
+		_usage "$0"
+		exit 1 ;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 if [ $# -eq 0 ]; then
-    _printhelp "$0"
-    exit
+	_usage "$0"
+	exit
 fi
 
 if ! command -v ffmpeg >/dev/null; then
-    echo "ffmpeg required."
-    exit
+	echo "ffmpeg required."
+	exit
 fi
 
-_highfreq()
-{
-    awk 'BEGIN{max=0} /crop=/ {t[$NF]++; if (t[$NF]>max) {max=t[$NF]; val=$NF}} END{print val}'
+_highfreq() {
+	awk 'BEGIN{max=0} /crop=/ {t[$NF]++; if (t[$NF]>max) {max=t[$NF]; val=$NF}} END{print val}'
 }
 
 ## Usage: _cropvalue FILE STEP
 ## Return the crop values as ffmpeg output them.
-_cropvalue()
-{
-    local step=$2
-    for i in $(seq $step $step $((5*$step))); do
-        ffmpeg -nostdin -ss $i -i "$1"  -t 10 -vf "cropdetect=24:2:0" -f null - 2>&1
-    done | _highfreq
+_cropvalue() {
+	local step=$2
+	for i in $(seq $step $step $((5*$step))); do
+		ffmpeg -nostdin -ss $i -i "$1"  -t 10 -vf "cropdetect=24:2:0" -f null - 2>&1
+	done | _highfreq
 }
 
 ## Return the audio encoding parameters. For instance
@@ -161,81 +158,79 @@ _cropvalue()
 ## If input codec is $AUDIO_CODEC, we copy. If some stream bitrates are missing
 ## or 0, we encode it to a default value. If default value is 0, then we copy
 ## stream.
-_audiobitrate()
-{
-    local bitrate
+_audiobitrate() {
+	local bitrate
 
-    for i in $(seq 0 $(($format_nb_streams-1)) ); do
-        ## Skip non audio tracks.
-        [ "$(eval echo \$streams_stream_${i}_codec_type)" != "audio" ] && continue
+	for i in $(seq 0 $(($format_nb_streams-1)) ); do
+		## Skip non audio tracks.
+		[ "$(eval echo \$streams_stream_${i}_codec_type)" != "audio" ] && continue
 
-        bitrate=$(eval echo \$streams_stream_${i}_bit_rate)
-        if [ -n "$bitrate" ] && [ "$bitrate" -gt 0 ] 2>/dev/null; then
-            ## If non-empty and a positive number.
-            bitrate=$(( $bitrate / 1000))
-        else
-            bitrate="$AUDIO_DEFAULT_RATE"
-        fi
-        if [ "$bitrate" -le 0 ] || \
-            [ "$AUDIO_CODEC" = "$(eval echo \$streams_stream_${i}_codec_name)" ] || \
-            [ "$AUDIO_CODEC" = "lib$(eval echo \$streams_stream_${i}_codec_name)" ]; then
-            printf -- "-c:%s copy " $i
-        else
-            [ $bitrate -gt 500 ] && bitrate=500
-            printf -- "-c:%s %s -b:%s %sk " $i "$AUDIO_CODEC" $i "$bitrate"
-        fi
-    done
+		bitrate=$(eval echo \$streams_stream_${i}_bit_rate)
+		if [ -n "$bitrate" ] && [ "$bitrate" -gt 0 ] 2>/dev/null; then
+			## If non-empty and a positive number.
+			bitrate=$(( $bitrate / 1000))
+		else
+			bitrate="$AUDIO_DEFAULT_RATE"
+		fi
+		if [ "$bitrate" -le 0 ] || \
+				 [ "$AUDIO_CODEC" = "$(eval echo \$streams_stream_${i}_codec_name)" ] || \
+				 [ "$AUDIO_CODEC" = "lib$(eval echo \$streams_stream_${i}_codec_name)" ]; then
+			printf -- "-c:%s copy " $i
+		else
+			[ $bitrate -gt 500 ] && bitrate=500
+			printf -- "-c:%s %s -b:%s %sk " $i "$AUDIO_CODEC" $i "$bitrate"
+		fi
+	done
 }
 
-_transcode()
-{
-    echo "==> [$1]"
-    OUTPUT="${1%.*}.$EXT"
-    [ -e "$OUTPUT" ] && OUTPUT="${1%.*}-$(date '+%F-%H%M%S').$EXT"
+_transcode() {
+	echo "==> [$1]"
+	OUTPUT="${1%.*}.$EXT"
+	[ -e "$OUTPUT" ] && OUTPUT="${1%.*}-$(date '+%F-%H%M%S').$EXT"
 
-    ## Metadata (i.e. tags + technical data).
-    _buffer="$(ffprobe -v quiet -print_format flat=s=_ -show_streams -show_format "$1")"
-    if [ $? -ne 0 ]; then
-        _error "File [$1] is unsupported by FFmpeg."
-        return
-    fi
-    eval "$_buffer"
-    unset _buffer
+	## Metadata (i.e. tags + technical data).
+	_buffer="$(ffprobe -v quiet -print_format flat=s=_ -show_streams -show_format "$1")"
+	if [ $? -ne 0 ]; then
+		_error "File [$1] is unsupported by FFmpeg."
+		return
+	fi
+	eval "$_buffer"
+	unset _buffer
 
-    STREAM_TITLE=""
-    if $OPT_REMOVE_TITLE; then
-        for i in $(seq 0 $(($format_nb_streams-1)) ); do
-            STREAM_TITLE="${STREAM_TITLE}-metadata:s:$i title= "
-        done
-    fi
+	STREAM_TITLE=""
+	if $OPT_REMOVE_TITLE; then
+		for i in $(seq 0 $(($format_nb_streams-1)) ); do
+			STREAM_TITLE="${STREAM_TITLE}-metadata:s:$i title= "
+		done
+	fi
 
-    if $OPT_CROP; then
-        echo "Computing crop values... "
-        ## For 5 different timeslices of 1 second at every 1/6th of the video,
-        ## we sample the crop values. We keep the values with highest
-        ## frequency. This is much faster than encoding in one pass with low
-        ## framerate.
-        STEP=${format_duration:-$streams_stream_0_duration}
-        STEP="${STEP%%.*}"
-        STEP=$(($STEP/6))
-        VIDEO_FILTER="-vf $(_cropvalue "$1" "$STEP")"
-        if $OPT_CROPPREVIEW; then
-            echo "Generating preview... "
-            for i in $(seq  $STEP $STEP $((5*$STEP))); do
-                ffmpeg -nostdin -v warning -y -ss $i -i "$1" \
-                    -f image2 -vframes 1 $VIDEO_FILTER "${1%.*}-preview-$i-cropped.png" \
-                    -f image2 -vframes 1 "${1%.*}-preview-$i-uncropped.png"
-            done
-        fi
-    fi
+	if $OPT_CROP; then
+		echo "Computing crop values... "
+		## For 5 different timeslices of 1 second at every 1/6th of the video,
+		## we sample the crop values. We keep the values with highest
+		## frequency. This is much faster than encoding in one pass with low
+		## framerate.
+		STEP=${format_duration:-$streams_stream_0_duration}
+		STEP="${STEP%%.*}"
+		STEP=$(($STEP/6))
+		VIDEO_FILTER="-vf $(_cropvalue "$1" "$STEP")"
+		if $OPT_CROPPREVIEW; then
+			echo "Generating preview... "
+			for i in $(seq  $STEP $STEP $((5*$STEP))); do
+				ffmpeg -nostdin -v warning -y -ss $i -i "$1" \
+					-f image2 -vframes 1 $VIDEO_FILTER "${1%.*}-preview-$i-cropped.png" \
+					-f image2 -vframes 1 "${1%.*}-preview-$i-uncropped.png"
+			done
+		fi
+	fi
 
-    ## WARNING: we mix down audio to 2 channels with '-ac 2'. This greatly
-    ## reduce file size and avoid any confusion for playback, which is often the
-    ## case when converting DTS to any other format because DTS has embedded
-    ## channel description which is not available in these formats.
-    ! $OPT_COPY && AUDIO_PARAM="$(_audiobitrate "$1") -ac 2"
+	## WARNING: we mix down audio to 2 channels with '-ac 2'. This greatly
+	## reduce file size and avoid any confusion for playback, which is often the
+	## case when converting DTS to any other format because DTS has embedded
+	## channel description which is not available in these formats.
+	! $OPT_COPY && AUDIO_PARAM="$(_audiobitrate "$1") -ac 2"
 
-    cat<<EOF
+	cat<<EOF
 ================================================================================
 User options:  ${TC_VIDEO_OPT:-none}
 Sample:        ${SAMPLE:-no}
@@ -249,47 +244,47 @@ Output file:   $OUTPUT
 ================================================================================
 EOF
 
-    $OPT_PREVIEW && return
+	$OPT_PREVIEW && return
 
-    ffmpeg -nostdin $OVERWRITE -i "$1" \
-        $VIDEO_PARAM $VIDEO_FILTER \
-        $AUDIO_PARAM \
-        -c:s copy \
-        -map 0 $STREAM_TITLE \
-        $SAMPLE $TC_VIDEO_OPT "$OUTPUT"
+	ffmpeg -nostdin $OVERWRITE -i "$1" \
+		$VIDEO_PARAM $VIDEO_FILTER \
+		$AUDIO_PARAM \
+		-c:s copy \
+		-map 0 $STREAM_TITLE \
+		$SAMPLE $TC_VIDEO_OPT "$OUTPUT"
 
-    if $OPT_OVERWRITE; then
-        rm "$1"
-        mv -f "$OUTPUT" "${1%.*}.$EXT"
-    fi
-    echo
+	if $OPT_OVERWRITE; then
+		rm "$1"
+		mv -f "$OUTPUT" "${1%.*}.$EXT"
+	fi
+	echo
 }
 
 for i in "$@"; do
 
-    ## Argument is a folder. We search for all video files in there.
-    if [ -d "$i" ]; then
+	## Argument is a folder. We search for all video files in there.
+	if [ -d "$i" ]; then
 
-        ## WARNING: ffmpeg continues to read stdin once it has started, so it should
-        ## not be called from within a while<<EOF loop without disabling stdin.
-        while IFS= read -r j; do
-            _transcode "$j"
-            done<<EOF
+		## WARNING: ffmpeg continues to read stdin once it has started, so it should
+		## not be called from within a while<<EOF loop without disabling stdin.
+		while IFS= read -r j; do
+			_transcode "$j"
+		done<<EOF
 $(find "$i"  \( \
-            -iname '*.avi' -o \
-            -iname '*.flv' -o \
-            -iname '*.mkv' -o \
-            -iname '*.mov' -o \
-            -iname '*.mp4' -o \
-            -iname '*.mpeg' -o \
-            -iname '*.mpg' -o \
-            -iname '*.webm' -o \
-            -iname '*.wmv' \) )
+		-iname '*.avi' -o \
+		-iname '*.flv' -o \
+		-iname '*.mkv' -o \
+		-iname '*.mov' -o \
+		-iname '*.mp4' -o \
+		-iname '*.mpeg' -o \
+		-iname '*.mpg' -o \
+		-iname '*.webm' -o \
+		-iname '*.wmv' \) )
 EOF
 
-    else
-        ## Argument is a regular file.
-        _transcode "$i"
-    fi
+	else
+		## Argument is a regular file.
+		_transcode "$i"
+	fi
 
 done
diff --git a/.scripts/trc b/.scripts/trc
--- a/.scripts/trc
+++ b/.scripts/trc
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ "$1" = "-h" ]; then
-    cat<<EOF
+	cat<<EOF
 Usage: ${0##*/} [OPTIONS]
 
 With no argument, start transmission-remote-cli. Otherwise, run
@@ -11,28 +11,27 @@ In both cases if transmission-daemon is not running it will be started
 beforehand.
 
 EOF
-    exit
+	exit
 fi
 
 
-check()
-{
-    for i ; do
-        if ! command -v $i >/dev/null 2>&1; then
-            echo >&2 "'$i' not found in PATH. Exiting."
-            exit 1
-        fi
-    done
+check () {
+	for i ; do
+		if ! command -v $i >/dev/null 2>&1; then
+			echo >&2 "'$i' not found in PATH. Exiting."
+			exit 1
+		fi
+	done
 }
+
 check transmission-daemon transmission-remote-cli
 
 [ $(ps -U $USER | grep -c transmission-da) -eq 0 ] && transmission-daemon
 if [ $# -eq 0 ]; then
-    exec transmission-remote-cli
+	exec transmission-remote-cli
 else
-    ## The 'sleep' is needed here to give the daemon some time to start. 1 sec
-    ## should be enough on most system.
-    sleep 1
-    transmission-remote "$@"
+	## The 'sleep' is needed here to give the daemon some time to start. 1 sec
+	## should be enough on most system.
+	sleep 1
+	transmission-remote "$@"
 fi
-
diff --git a/.scripts/zshcd b/.scripts/zshcd
--- a/.scripts/zshcd
+++ b/.scripts/zshcd
@@ -3,8 +3,8 @@
 ## browsers to start shell in pointed folder.
 
 if [ ! -d "$1" ]; then
-    zsh
-    exit
+	zsh
+	exit
 fi
 
 ## Default files.
@@ -12,30 +12,30 @@ ZDIRS="$HOME/.cache/zsh/dirs"
 
 ## Fetch file location dynamically.
 if [ ! -f ~/.zshrc ]; then
-    echo '~/.zshrc not found. Exiting.'
-    exit 1
+	echo '~/.zshrc not found. Exiting.'
+	exit 1
 fi
 
 ## We need realpath to prevent us from adding duplicates to the zsh
 ## DIRSTACKFILE.
 if ! command -v realpath >/dev/null 2>&1; then
-    echo "'realpath' not found. Exiting."
-    exit 1
+	echo "'realpath' not found. Exiting."
+	exit 1
 fi
 
 SHELL_DIR_GREP="$(grep "SHELL_DIR=" ~/.zshrc | cut -f2 -d=)"
 [ -n "$SHELL_DIR_GREP" ] && SHELL_DIR="$(eval echo "$SHELL_DIR_GREP")"
 if [ ! -d "$SHELL_DIR" ]; then
-    echo 'SHELL_DIR not found. Could not search for DIRSTACKFILE. Exiting.'
-    exit 1
+	echo 'SHELL_DIR not found. Could not search for DIRSTACKFILE. Exiting.'
+	exit 1
 fi
 
 ZDIRS_GREP="$(grep -rm1 'DIRSTACKFILE=' "$SHELL_DIR" | cut -f2 -d=)"
 [ -n "$ZDIRS_GREP" ] && ZDIRS="$(eval echo "$ZDIRS_GREP")"
 
 if [ ! -f "$ZDIRS" ]; then
-    echo 'DIRSTACKFILE not found. Exiting.'
-    exit 1
+	echo 'DIRSTACKFILE not found. Exiting.'
+	exit 1
 fi
 
 ## Prepend argument to zsh dirstack.
