Script+Shell: fixed and standardize PATH checking
We redirect stderr to NULL since POSIX says it may be used (no modern shell
seems to be using it).

If more than 1 program is checked for availability, we use a function.

Emacs snippet make it uniform.

Error message is output on stderr and is always the same.

diff --git a/.scripts/.tc-video-custom.in b/.scripts/.tc-video-custom.in
--- a/.scripts/.tc-video-custom.in
+++ b/.scripts/.tc-video-custom.in
@@ -48,9 +48,9 @@ if ! $OPT_PROCESS; then
     exit
 fi
 
-if ! command -v ffmpeg >/dev/null; then
-    echo "ffmpeg required."
-    exit
+if ! command -v ffmpeg >/dev/null 2>&1; then
+    echo >&2 "'ffmpeg' not found in PATH. Exiting."
+    exit 1
 fi
 
 _transcode ()
diff --git a/.scripts/archive b/.scripts/archive
--- a/.scripts/archive
+++ b/.scripts/archive
@@ -63,8 +63,8 @@ fi
 ## We need 'realpath' since we need to work on the real path for the input
 ## files/folders and the archive location. Otherwise we could have troubles with
 ## circular symlinks and so on.
-if ! command -v realpath >/dev/null; then
-    echo >&2 "'realpath' is required."
+if ! command -v realpath >/dev/null 2>&1; then
+    echo >&2 "'realpath' not found in PATH. Exiting."
     exit 1
 fi
 
diff --git a/.scripts/clonecd b/.scripts/clonecd
--- a/.scripts/clonecd
+++ b/.scripts/clonecd
@@ -39,13 +39,10 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-
-if ! command -v readcd >/dev/null; then
-    echo >&2 "readcd required."
-    exit
+if ! command -v readcd >/dev/null 2>&1; then
+    echo >&2 "'readcd' not found in PATH. Exiting."
+    exit 1
 fi
-
-
 
 ## Fast?
 readcd dev=$DRIVE f="$1.iso" -v retries=5 timeout=30 -noerror
diff --git a/.scripts/git-get b/.scripts/git-get
--- a/.scripts/git-get
+++ b/.scripts/git-get
@@ -43,12 +43,10 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-
-if ! command -v git >/dev/null; then
-    echo >&2 "git required."
-    exit
+if ! command -v git >/dev/null 2>&1; then
+    echo >&2 "'git' not found in PATH. Exiting."
+    exit 1
 fi
-
 
 for i; do
     git clone git@$DOMAIN:/$USER/$i
diff --git a/.scripts/imagemount b/.scripts/imagemount
--- a/.scripts/imagemount
+++ b/.scripts/imagemount
@@ -34,7 +34,7 @@ _mount ()
     fi
 
     cdemu load $DEVICE "$1"
-    if [ $? -ne 0 ] && command -v fuseiso >/dev/null; then
+    if [ $? -ne 0 ] && command -v fuseiso >/dev/null 2>&1; then
         echo "Falling back to fuseiso."
 
         # LIST="$(mount | awk -v root="$FUSEROOT" '$1 == "fuseiso" && $3 ~ root {print $3}')"
@@ -83,16 +83,6 @@ _umount ()
     fi
 }
 
-
-if ! command -v udiskie >/dev/null; then
-    echo "udiskie required."
-    exit
-fi
-if ! command -v cdemu >/dev/null; then
-    echo "cdemu required."
-    exit
-fi
-
 _printhelp ()
 {
     cat<<EOF
@@ -134,13 +124,18 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-if ! command -v realpath >/dev/null; then
-    echo >&2 "'realpath' is required."
-    exit 1
-fi
-
-
+check()
+{
+    for i ; do
+        if ! command -v $i >/dev/null 2>&1; then
+            echo >&2 "'$i' not found in PATH. Exiting."
+            exit 1
+        fi
+    done
+}
 ## realpath is needed to check if image was already mounted or not.
+check udiskie cdemu realpath
+
 if $OPT_UNMOUNT; then
     for i ; do
         _umount "$(realpath "$i")"
diff --git a/.scripts/netinit b/.scripts/netinit
--- a/.scripts/netinit
+++ b/.scripts/netinit
@@ -27,7 +27,7 @@ Usage: ${1##*/} [OPTIONS]
 
 Connect to a wireless network.
 
-  -c:       Decrypt $WSFILE with ccrypt.
+  -c:       Decrypt $WSFILE with ccrypt's ccat command'.
   -d:       Use DHCP.
   -h:       Show this help.
   -t ITER:  Timeout (default: $TIMEOUT_LIMIT).
@@ -73,10 +73,11 @@ if [ $(id -u) -ne 0 ]; then
 fi
 
 if [ $USE_CRYPT -eq 1 ]; then
-    if ! command -v ccrypt >/dev/null; then
-        echo "You need to have 'ccrypt' installed."
-        exit
+    if ! command -v ccat >/dev/null 2>&1; then
+        echo >&2 "'ccat' not found in PATH. Exiting."
+        exit 1
     fi
+
     WPA_SUPPLICANT_CONF="$(ccat "$WSFILE")"
     if [ $? -ne 0 ]; then
         echo "Failed to decrypt wpa_supplicant config from $WSFILE."
diff --git a/.scripts/netmap b/.scripts/netmap
--- a/.scripts/netmap
+++ b/.scripts/netmap
@@ -12,9 +12,9 @@ EOF
 fi
 
 ## Network operations
-if ! command -v nmap >/dev/null; then
-    echo "nmap required."
-    exit
+if ! command -v nmap >/dev/null 2>&1; then
+    echo >&2 "'nmap' not found in PATH. Exiting."
+    exit 1
 fi
 
 echo "$1"
diff --git a/.scripts/pacman-diff b/.scripts/pacman-diff
--- a/.scripts/pacman-diff
+++ b/.scripts/pacman-diff
@@ -47,7 +47,10 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-! command -v pacman >/dev/null && echo "You need pacman to run this script." && exit 1
+if ! command -v pacman >/dev/null 2>&1; then
+    echo >&2 "'pacman' not found in PATH. Exiting."
+    exit 1
+fi
 
 PKGLIST="$(mktemp)"
 FILE="$(mktemp)"
diff --git a/.scripts/prettyc b/.scripts/prettyc
--- a/.scripts/prettyc
+++ b/.scripts/prettyc
@@ -18,10 +18,9 @@ if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
     exit
 fi
 
-
-if ! command -v indent >/dev/null; then
-    echo "Please install 'indent'."
-    exit
+if ! command -v indent >/dev/null 2>&1; then
+    echo >&2 "'indent' not found in PATH. Exiting."
+    exit 1
 fi
 
 CMD="indent -i4 -ppi4 -bli0 -cli4 -nut"
