scripts: Overhaul (syntax, exit code, help to stderr, errors, -- arg)

diff --git a/.scripts/.tc-video-custom.in b/.scripts/.tc-video-custom.in
--- a/.scripts/.tc-video-custom.in
+++ b/.scripts/.tc-video-custom.in
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-_usage () {
-	cat <<EOF
-Usage: ${1##*/} MODE
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} MODE
 
 This script was generated with tc-video-custom.
 
@@ -24,8 +24,8 @@ OPT_PROCESS=false
 while getopts ":hfsS:" opt; do
 	case $opt in
 	h)
-		_usage "$0"
-		exit 1 ;;
+		usage
+		exit ;;
 	f)
 		OPT_PROCESS=true ;;
 	s)
@@ -35,7 +35,7 @@ while getopts ":hfsS:" opt; do
 		SAMPLE="-ss 60 -t $((60*$OPTARG))"
 		OPT_PROCESS=true ;;
 	\?)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -43,16 +43,16 @@ done
 shift $(($OPTIND - 1))
 
 if ! $OPT_PROCESS; then
-	_usage "$0"
+	usage
 	exit
 fi
 
 if ! command -v ffmpeg >/dev/null 2>&1; then
-	echo >&2 "'ffmpeg' not found in PATH. Exiting."
+	echo >&2 "'ffmpeg' not found"
 	exit 1
 fi
 
-_transcode () {
+transcode () {
 	## You can choose here to process all files at the same time. Useful if you
 	## need to remux streams or to concatenate.
 	# ffmpeg -i ###FILELIST \
@@ -69,12 +69,12 @@ set -- ###FILENAMES
 
 ## Choose to process all files one after another.
 for i ; do
-	_transcode "$i"
+	transcode "$i"
 done
 
 ## Or all files at the same time. You have to change the ffmpeg input in the
 ## function.
-# _transcode
+# transcode
 
 ################################################################################
 ## USE CASES
diff --git a/.scripts/archive b/.scripts/archive
--- a/.scripts/archive
+++ b/.scripts/archive
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-_usage () {
-	cat <<EOF
-Usage: ${1##*/} [-m METHOD] [-v] FILES|FOLDERS
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [-m METHOD] [-v] FILES|FOLDERS
 
 Create an archive in current folder from a single or multiples
 files/folders. Each input entry will be at archive root (no absolute path is
@@ -28,8 +28,8 @@ OPT_SPLIT=false
 while getopts ":him:sv" opt; do
 	case $opt in
 	h)
-		_usage "$0"
-		exit 1 ;;
+		usage
+		exit ;;
 	i)
 		OPTIONS="$OPTIONS --owner=root --group=root --numeric-owner" ;;
 	m)
@@ -42,7 +42,7 @@ while getopts ":him:sv" opt; do
 	v)
 		OPTIONS="$OPTIONS --exclude-vcs" ;;
 	\?)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -51,7 +51,7 @@ done
 shift $((OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-	_usage "$0"
+	usage
 	exit 1
 fi
 
@@ -59,11 +59,11 @@ fi
 ## files/folders and the archive location. Otherwise we could have troubles with
 ## circular symlinks and so on.
 if ! command -v realpath >/dev/null 2>&1; then
-	echo >&2 "'realpath' not found in PATH. Exiting."
+	echo >&2 "'realpath' not found"
 	exit 1
 fi
 
-_archive () {
+archive () {
 	## Only one input entry: use it as base name for the archive.
 	if [ $# -eq 1 ]; then
 		REALPATH="$(realpath "$1")"
@@ -93,7 +93,7 @@ _archive () {
 	echo "==> [$OUTPATH/$OUTFILE]"
 	for i; do
 		REALPATH="$(realpath "$i")"
-		echo "${REALPATH}" >&2
+		echo >&2 "${REALPATH}"
 		echo "-C '${REALPATH%/*}'"
 		echo "${REALPATH##*/}"
 	done | tar $OPTIONS -${ARCOPT}cf "$OUTPATH/$OUTFILE" -T -
@@ -101,8 +101,8 @@ _archive () {
 
 if $OPT_SPLIT; then
 	for j ; do
-		_archive "$j"
+		archive "$j"
 	done
 else
-	_archive "$@"
+	archive "$@"
 fi
diff --git a/.scripts/clonecd b/.scripts/clonecd
--- a/.scripts/clonecd
+++ b/.scripts/clonecd
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-_usage () {
-	cat<<EOF
-Usage: ${1##*/} [OPTIONS] ISOFILE
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [OPTIONS] ISOFILE
 
 Dump optical disc to ISOFILE (without extension).
 
@@ -18,12 +18,12 @@ DRIVE=/dev/sr0
 while getopts ":hd:" opt; do
 	case $opt in
 	h)
-		_usage "$0"
-		exit 1 ;;
+		usage
+		exit ;;
 	d)
 		DRIVE=/dev/$OPTARG ;;
 	\?)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -31,12 +31,12 @@ done
 shift $((OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-	_usage "$0"
+	usage
 	exit 1
 fi
 
 if ! command -v readcd >/dev/null 2>&1; then
-	echo >&2 "'readcd' not found in PATH. Exiting."
+	echo >&2 "'readcd' not found"
 	exit 1
 fi
 
diff --git a/.scripts/dataindex b/.scripts/dataindex
--- a/.scripts/dataindex
+++ b/.scripts/dataindex
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-_usage () {
-	cat<<EOF
-Usage: ${1##*/} [OPTIONS] FOLDERS
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [OPTIONS] FOLDERS
 
 Output index of folder hierarchies to stdout. This is used as a small "backup"
 purpose. In case of data loss, it is still possible to get the full file list
@@ -23,12 +23,12 @@ while getopts ":fhw" opt; do
 	f)
 		opt_noclobber=false ;;
 	h)
-		_usage "$0"
-		exit 0 ;;
+		usage
+		exit ;;
 	w)
 		opt_file=true ;;
 	\?)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -36,13 +36,13 @@ done
 shift $((OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-	_usage "$0"
+	usage
 	exit 1
 fi
 
 ## 'realpath' is required in case argument is ending with '.' or '..'.
 if ! command -v realpath >/dev/null 2>&1; then
-	echo "'realpath' not found in PATH. Exiting." >&2
+	echo >&2 "'realpath' not found"
 	exit 1
 fi
 
diff --git a/.scripts/einfo b/.scripts/einfo
--- a/.scripts/einfo
+++ b/.scripts/einfo
@@ -1,15 +1,11 @@
 #!/bin/sh
 
-check() {
-	for i ; do
-		if ! command -v $i >/dev/null 2>&1; then
-			echo "'$i' not found in PATH. Exiting." >&2
-			exit 1
-		fi
-	done
-}
-
-check emacs realpath
+for i in emacs realpath ; do
+	if ! command -v $i >/dev/null 2>&1; then
+		echo >&2 "'$i' not found"
+		exit 1
+	fi
+done
 
 [ -f "$1" ] && node="$(realpath "$1")" || node="$1"
 emacs --eval '(progn (info "'"$node"'")(delete-other-windows))'
diff --git a/.scripts/elisp b/.scripts/elisp
--- a/.scripts/elisp
+++ b/.scripts/elisp
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-_usage () {
-	cat<<EOF
-Usage: ${1##*/} [OPTIONS] SCRIPT [ARGS...]
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [OPTIONS] SCRIPT [ARGS...]
 
 Run Emacs Lisp SCRIPT.
 
@@ -22,31 +22,30 @@ while getopts :bc OPT; do
 	c)
 		OPT_CLEAN=true ;;
 	\?)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
 
 shift $((OPTIND - 1))
 if [ $# -eq 0 ]; then
-	_usage "$0"
+	usage
 	exit 1
 fi
 
 if ! command -v emacs >/dev/null 2>&1; then
-	echo 'emacs not found in PATH. Exiting.' >&2
+	echo >&2 'emacs not found'
 	exit 1
 fi
 
 script="$1"
-if $OPT_BYTE && [ "${1##*.}" = "el" ]; then
+if $OPT_BYTE && [ "${0##*.}" = "el" ]; then
 	script="${1%.*}.elc"
 	emacs -Q --batch -f batch-byte-compile "$1" 2>/dev/null
 fi
 shift
 
 emacs -Q --script "$script" "$@" 2>&1
+status=$?
 $OPT_CLEAN && rm "$script"
-
-## WARNING: never leave a script on a condition, return code be unexpectedly != 0.
-exit 0
+exit $status
diff --git a/.scripts/git-get b/.scripts/git-get
--- a/.scripts/git-get
+++ b/.scripts/git-get
@@ -3,9 +3,9 @@
 DOMAIN=bitbucket.org
 USER=ambrevar
 
-usage() {
-	cat<<EOF
-Usage: ${1##*/} [OPTIONS] REPOS
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [OPTIONS] REPOS
 
 Clone git repo(s) from $DOMAIN:$USER.
 
@@ -21,14 +21,14 @@ EOF
 while getopts ":hd:u:" opt; do
 	case $opt in
 	h)
-		usage "$0"
+		usage
 		exit 1 ;;
 	d)
 		DOMAIN=$OPTARG ;;
 	u)
 		USER=$OPTARG ;;
 	\?)
-		usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -36,12 +36,12 @@ done
 shift $((OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-	usage "$0"
+	usage
 	exit 1
 fi
 
 if ! command -v git >/dev/null 2>&1; then
-	echo >&2 "'git' not found in PATH. Exiting."
+	echo >&2 "'git' not found"
 	exit 1
 fi
 
diff --git a/.scripts/imagemount b/.scripts/imagemount
--- a/.scripts/imagemount
+++ b/.scripts/imagemount
@@ -3,7 +3,7 @@
 ## User options:
 FUSEROOT="$HOME/fuse"
 
-_mount () {
+mount () {
 	[ ! -f "$1" ] && return
 
 	DEVICE="$(cdemu status | awk 'NR>2 && $2==0 {print $1; found=1; exit}  END {if(! found)print NR-2}')"
@@ -62,7 +62,7 @@ _mount () {
 }
 
 
-_umount () {
+umount () {
 	[ ! -d "$1" ] && return
 
 	NODE="$(df | awk -v mount="$1" '$0 ~ mount {node=$1; gsub(/[^%]+% /, ""); if ($0 ~ mount){print node; exit}}')"
@@ -78,10 +78,10 @@ _umount () {
 	fi
 }
 
-_usage () {
-	cat<<EOF
-Usage: ${1##*/} FILES
-       ${1##*/} -u FOLDERS
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} FILES
+       ${0##*/} -u FOLDERS
 
 Mount image files using CDEmu or fall back to fuseriso if available.  It will
 not mount an image if already mounted.
@@ -98,12 +98,12 @@ OPT_UNMOUNT=false
 while getopts ":hu" opt; do
 	case $opt in
 	h)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	u)
 		OPT_UNMOUNT=true ;;
 	\?)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -111,27 +111,24 @@ done
 shift $((OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-	_usage "$0"
+	usage
 	exit 1
 fi
 
-check () {
-	for i ; do
-		if ! command -v $i >/dev/null 2>&1; then
-			echo >&2 "'$i' not found in PATH. Exiting."
-			exit 1
-		fi
-	done
-}
 ## realpath is needed to check if image was already mounted or not.
-check udiskie cdemu realpath
+for i in udiskie cdemu realpath; do
+	if ! command -v $i >/dev/null 2>&1; then
+		echo >&2 "'$i' not found"
+		exit 1
+	fi
+done
 
 if $OPT_UNMOUNT; then
 	for i ; do
-		_umount "$(realpath "$i")"
+		umount "$(realpath "$i")"
 	done
 else
 	for i ; do
-		_mount "$(realpath "$i")"
+		mount "$(realpath "$i")"
 	done
 fi
diff --git a/.scripts/netinit b/.scripts/netinit
--- a/.scripts/netinit
+++ b/.scripts/netinit
@@ -23,9 +23,9 @@ TIMEOUT_LIMIT=500
 USE_DHCP=0
 USE_CRYPT=0
 
-_usage () {
-	cat<<EOF
-Usage: ${1##*/} [OPTIONS]
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [OPTIONS]
 
 Connect to a wireless network.
 
@@ -41,7 +41,7 @@ EOF
 while getopts ":cdht:w:" opt; do
 	case $opt in
 	h)
-		_usage "$0"
+		usage
 		return 1 ;;
 	c)
 		USE_CRYPT=1 ;;
@@ -52,7 +52,7 @@ while getopts ":cdht:w:" opt; do
 	w)
 		WSFILE="$OPTARG" ;;
 	\?)
-		_usage "$0"
+		usage
 		return 1 ;;
 	esac
 done
@@ -66,7 +66,7 @@ fi
 
 if [ $USE_CRYPT -eq 1 ]; then
 	if ! command -v ccat >/dev/null 2>&1; then
-		echo >&2 "'ccat' not found in PATH. Exiting."
+		echo >&2 "'ccat' not found"
 		exit 1
 	fi
 
diff --git a/.scripts/netmap b/.scripts/netmap
--- a/.scripts/netmap
+++ b/.scripts/netmap
@@ -1,17 +1,20 @@
 #!/bin/sh
 
-if [ $# -ne 1 ] || [ "$1" = "-h" ] ; then
-	cat<<EOF
-Usage: ${1##*/} IP
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} IP
 
 Print the map of the network associated to the provided IP.
 EOF
-	exit
-fi
+}
+
+[ $# -ne 1 ] && usage && exit 1
+[ "$1" = "-h" ] && usage && exit
+[ "$1" = "--" ] && shift
 
 ## Network operations
 if ! command -v nmap >/dev/null 2>&1; then
-	echo >&2 "'nmap' not found in PATH. Exiting."
+	echo >&2 "'nmap' not found"
 	exit 1
 fi
 
diff --git a/.scripts/netscan b/.scripts/netscan
--- a/.scripts/netscan
+++ b/.scripts/netscan
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if ! command -v nmap >/dev/null 2>&1; then
-	echo >&2 "'nmap' not found in PATH. Exiting."
+	echo >&2 "'nmap' not found"
 	exit 1
 fi
 
diff --git a/.scripts/netspeed b/.scripts/netspeed
--- a/.scripts/netspeed
+++ b/.scripts/netspeed
@@ -1,14 +1,16 @@
 #!/bin/sh
 
-if [ "$1" = "-h" ] || [ $# -gt 1 ]; then
-	cat<<EOF
+usage () {
+	cat <<EOF>&2
 Usage: ${0##*/} [INTERFACE]
 
 Return up and down transmission speed on given interface. If not given, use the
 first online interface returned by ifconfig (lo is ignored).
 EOF
-	exit
-fi
+}
+ 
+[ $# -gt 1 ] && usage && exit 1
+[ "$1" = "-h" ] && usage && exit
 
 if [ -n "$1" ]; then
 	interface="$1"
@@ -19,7 +21,7 @@ else
 fi
 
 if [ ! -d "/sys/class/net/${interface}" ]; then
-	echo "Error: no such interface: ${interface}" >&2
+	echo >&2 "Error: no such interface: ${interface}"
 else
 	path="/dev/shm/netspeed"
 	time=$(date +%s)
diff --git a/.scripts/pacman-diff b/.scripts/pacman-diff
--- a/.scripts/pacman-diff
+++ b/.scripts/pacman-diff
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-_usage () {
-	cat <<EOF
-Usage: ${1##*/} [-m|-e] [-q] FILE
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [-m|-e] [-q] FILE
 
 Display packages listed in FILE but not installed.
 
@@ -22,14 +22,14 @@ while getopts ":hmqe" opt; do
 	e)
 		OPTION_EXPLICIT="e" ;;
 	h)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	m)
 		OPTION_FOREIGN="m" ;;
 	q)
 		OPTION_LOCAL="-2" ;;
 	\?)
-		_usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -38,12 +38,12 @@ shift $((OPTIND - 1))
 
 if [ $# -eq 0 ]; then
 	echo "Missing argument."
-	_usage "$0"
+	usage
 	exit 1
 fi
 
 if ! command -v pacman >/dev/null 2>&1; then
-	echo >&2 "'pacman' not found in PATH. Exiting."
+	echo >&2 "'pacman' not found"
 	exit 1
 fi
 
diff --git a/.scripts/pacsize b/.scripts/pacsize
--- a/.scripts/pacsize
+++ b/.scripts/pacsize
@@ -46,7 +46,7 @@ END {
 }
 
 error () {
-	echo "$@" >&2
+	echo >&2 "$@"
 }
 
 ## Print size and name. We round to the lowest integer, this makes output
@@ -67,9 +67,9 @@ remove_duplicates () {
 }
 
 usage () {
-	cat <<EOF
-Usage: ${1##*/} [OPTIONS] PACKAGES
-       ${1##*/} -a [OPTIONS]
+	cat <<EOF>&2
+Usage: ${0##*/} [OPTIONS] PACKAGES
+       ${0##*/} -a [OPTIONS]
 
 Display the size of PACKAGES. Duplicates are removed if any. The local database
 is queried first; if the package is not found, the sync database is then used
@@ -86,13 +86,13 @@ Options:
 
 Examples:
 
-  $ ${1##*/} -ast
+  $ ${0##*/} -ast
     Convenient way to keep track of big packages.
 
-  $ ${1##*/} \$(pactree -ld1 linux)
+  $ ${0##*/} \$(pactree -ld1 linux)
     Print the size of linux and all its direct dependencies.
 
-  $ ${1##*/} -st \$(pacman -Qdtq)
+  $ ${0##*/} -st \$(pacman -Qdtq)
     Print a grand total of orphan packages, and sort by size.
 EOF
 }
@@ -111,7 +111,7 @@ while getopts ":ahnstV" opt; do
 	a)
 		opt_all=true ;;
 	h)
-		usage "$0"
+		usage
 		exit ;;
 	n)
 		opt_sort="sort -k3" ;;
@@ -123,7 +123,7 @@ while getopts ":ahnstV" opt; do
 		version "$0"
 		exit ;;
 	\?)
-		usage "$0"
+		usage
 		exit 1 ;;
 	esac
 done
@@ -163,13 +163,13 @@ fi
 ## Per-package mode.
 if [ $# -eq 0 ]; then
 	error "Missing argument."
-	usage "$0"
+	usage
 	exit 1
 fi
 
 ## Remove this check if integrated to pacman.
 if ! command -v pacman >/dev/null 2>&1; then
-	error "'pacman' not found."
+	error "'pacman' not found"
 	exit 1
 fi
 
diff --git a/.scripts/pdfsize b/.scripts/pdfsize
--- a/.scripts/pdfsize
+++ b/.scripts/pdfsize
@@ -1,16 +1,19 @@
 #!/bin/sh
 
-if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
-	cat<<EOF
+usage () {
+	cat <<EOF>&2
 Usage: ${0##*/} [options] <PDF-file>
 
 Same as pdfinfo, but append size in milimeters.
 EOF
-	exit
-fi
+}
+
+[ $# -eq 0 ] && usage && exit 1
+[ "$1" = "-h" ] && usage && exit
+[ "$1" = "--" ] && shift
 
 if ! command -v pdfinfo >/dev/null 2>&1; then
-	echo 'pdfinfo not found in PATH. Exiting.' >&2
+	echo >&2 'pdfinfo not found'
 	exit 1
 fi
 
diff --git a/.scripts/renamelowerrec b/.scripts/renamelowerrec
--- a/.scripts/renamelowerrec
+++ b/.scripts/renamelowerrec
@@ -1,18 +1,20 @@
 #!/bin/sh
 
-if [ $# -eq 0 ] || [ "$1" = "-h" ] ; then
-	cat<<EOF
-Usage: ${1##*/} FOLDERS
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} FOLDERS
 
 Rename to lowercase all files found in FOLDERS if destination does not exists.
 
 EOF
+}
 
-	exit
-fi
+[ $# -eq 0 ] && usage && exit 1
+[ "$1" = "-h" ] && usage && exit
+[ "$1" = "--" ] && shift
 
 if ! command -v renamelower >/dev/null 2>&1; then
-	echo "'renamelower' not found in PATH. Exiting." >&2
+	echo >&2 "'renamelower' not found"
 	exit 1
 fi
 
diff --git a/.scripts/tc-video-custom b/.scripts/tc-video-custom
--- a/.scripts/tc-video-custom
+++ b/.scripts/tc-video-custom
@@ -2,9 +2,9 @@
 
 OUTPUT_NAME="tc-video"
 
-if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
-	cat <<EOF
-Usage: ${1##*/} [FILES]
+usage () {
+	cat <<EOF>&2
+Usage: ${0##*/} [FILES]
 
 Create a '$OUTPUT_NAME' script in current folder. The script provides a FFmpeg call
 to transcode FILES with some useful options and instructive help.
@@ -12,10 +12,13 @@ to transcode FILES with some useful options and instructive help.
 This script is meant to be easily editable to fit the user needs.
 
 EOF
-	exit
-fi
+}
 
-_escname () {
+[ $# -eq 0 ] && usage && exit 1
+[ "$1" = "-h" ] && usage && exit
+[ "$1" = "--" ] && shift
+
+escname () {
 	echo "$@" | sed 's|/|\\/|g'
 }
 
@@ -25,12 +28,12 @@ FILELIST=""
 if [ -f "$SCRIPT_PATH/.$SCRIPT_NAME.in" ]; then
 	cp -i "$SCRIPT_PATH/.$SCRIPT_NAME.in" "$OUTPUT_NAME"
 	for i ; do
-		esci="$(_escname "$i")"
+		esci="$(escname "$i")"
 		FILELIST="${FILELIST:+$FILELIST -i }'$esci'"
 		ex -sc "%s/###FILENAMES/'$esci' ###FILENAMES/ | xit" "$OUTPUT_NAME"
 	done
 	ex -sc '%s/###FILELIST/'"$FILELIST"'/ | xit' "$OUTPUT_NAME"
 	chmod +x "$OUTPUT_NAME"
 else
-	echo ".$SCRIPT_NAME.in not found!"
+	echo ".$SCRIPT_NAME.in not found"
 fi
diff --git a/.scripts/trc b/.scripts/trc
--- a/.scripts/trc
+++ b/.scripts/trc
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ "$1" = "-h" ]; then
-	cat<<EOF
+	cat <<EOF>&2
 Usage: ${0##*/} [OPTIONS]
 
 With no argument, start transmission-remote-cli. Otherwise, run
@@ -14,19 +14,14 @@ EOF
 	exit
 fi
 
+for i in check transmission-daemon transmission-remote-cli ; do
+	if ! command -v $i >/dev/null 2>&1; then
+		echo >&2 "'$i' not found"
+		exit 1
+	fi
+done
 
-check () {
-	for i ; do
-		if ! command -v $i >/dev/null 2>&1; then
-			echo >&2 "'$i' not found in PATH. Exiting."
-			exit 1
-		fi
-	done
-}
-
-check transmission-daemon transmission-remote-cli
-
-ps -U "$USER" | grep -q transmission-da || transmission-daemon
+ps -U "$USER" -o comm= | grep -q transmission-da || transmission-daemon
 if [ $# -eq 0 ]; then
 	exec transmission-remote-cli
 else
diff --git a/.scripts/winefps b/.scripts/winefps
--- a/.scripts/winefps
+++ b/.scripts/winefps
@@ -1,16 +1,20 @@
 #!/bin/sh
 
-if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
-	cat<<EOF
+usage () {
+	cat <<EOF>&2
 Usage: ${0##*/} WIN_EXE PARAMS"
 
 Run Wine application while displaying FPS onscreen.
+
 EOF
-	exit
-fi
+}
+
+[ $# -eq 0 ] && usage && exit 1
+[ "$1" = "-h" ] && usage && exit
+[ "$1" = "--" ] && shift
 
 if ! command -v osd_cat >/dev/null 2>&1; then
-	echo >&2 "osd_cat not found in path."
+	echo >&2 "osd_cat not found"
 	exit 1
 fi
 
