Scripts: fixed realpath usage

diff --git a/.scripts/archive b/.scripts/archive
--- a/.scripts/archive
+++ b/.scripts/archive
@@ -60,6 +60,13 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
+## We need 'realpath' since we need to work on the real path for the input
+## files/folders and the archive location. Otherwise we could have troubles with
+## circular symlinks and so on.
+if ! command -v realpath >/dev/null; then
+    echo >&2 "'realpath' is required."
+    exit 1
+fi
 
 _archive()
 {
diff --git a/.scripts/imagemount b/.scripts/imagemount
--- a/.scripts/imagemount
+++ b/.scripts/imagemount
@@ -134,6 +134,13 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
+if ! command -v realpath >/dev/null; then
+    echo >&2 "'realpath' is required."
+    exit 1
+fi
+
+
+## realpath is needed to check if image was already mounted or not.
 if $OPT_UNMOUNT; then
     for i ; do
         _umount "$(realpath "$i")"
diff --git a/.scripts/zshcd b/.scripts/zshcd
--- a/.scripts/zshcd
+++ b/.scripts/zshcd
@@ -12,19 +12,21 @@ ZDIRS="$HOME/.cache/zsh/dirs"
 ## Fetch file location dynamically.
 if [ ! -f ~/.zshrc ]; then
     echo '~/.zshrc not found. Exiting.'
-    exit
-fi
-if ! command -v realpath; then
-    echo "'realpath' not found. Exiting."
-    exit
+    exit 1
 fi
 
+## We need realpath to prevent us from adding duplicates to the zsh
+## DIRSTACKFILE.
+if ! command -v realpath; then
+    echo "'realpath' not found. Exiting."
+    exit 1
+fi
 
 SHELL_DIR_GREP="$(grep "SHELL_DIR=" ~/.zshrc | cut -f2 -d=)"
 [ -n "$SHELL_DIR_GREP" ] && SHELL_DIR="$(eval echo "$SHELL_DIR_GREP")"
 if [ ! -d "$SHELL_DIR" ]; then
     echo 'SHELL_DIR not found. Could not search for DIRSTACKFILE. Exiting.'
-    exit
+    exit 1
 fi
 
 ZDIRS_GREP="$(grep -rm1 'DIRSTACKFILE=' "$SHELL_DIR" | cut -f2 -d=)"
@@ -32,7 +34,7 @@ ZDIRS_GREP="$(grep -rm1 'DIRSTACKFILE=' "$SHELL_DIR" | cut -f2 -d=)"
 
 if [ ! -f "$ZDIRS" ]; then
     echo 'DIRSTACKFILE not found. Exiting.'
-    exit
+    exit 1
 fi
 
 ## Prepend argument to zsh dirstack.
