renamelowerrec: check for renamelower existence

diff --git a/.scripts/renamelowerrec b/.scripts/renamelowerrec
--- a/.scripts/renamelowerrec
+++ b/.scripts/renamelowerrec
@@ -11,6 +11,11 @@ EOF
     exit
 fi
 
+if command -v renamelower >/dev/null 2>&1; then
+    echo "'renamelower' not found in PATH. Exiting." >&2
+    exit 1
+fi
+
 for i ; do
     find "$i" -depth -exec renamelower {} +
 done
